version: '3'

services:
  mysql:
    image: mysql:8.0
    container_name: weaver-pokemon-type-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: pokemon_type
    ports:
      - 3306:3306
