package domain

// Code generated by "weaver generate". DO NOT EDIT.
import (
	"fmt"
	"github.com/ServiceWeaver/weaver/runtime/codegen"
)


// Local stub implementations.

// Client stub implementations.

// Server stub implementations.

// AutoMarshal implementations.

var _ codegen.AutoMarshal = &Effectivity{}

func (x *Effectivity) WeaverMarshal(enc *codegen.Encoder) {
	if x == nil {
		panic(fmt.Errorf("Effectivity.WeaverMarshal: nil receiver"))
	}
	enc.Int(x.ID)
	(x.Attack).WeaverMarshal(enc)
	(x.Defense).WeaverMarshal(enc)
	enc.Float32(x.Multiplier)
}

func (x *Effectivity) WeaverUnmarshal(dec *codegen.Decoder) {
	if x == nil {
		panic(fmt.Errorf("Effectivity.WeaverUnmarshal: nil receiver"))
	}
	x.ID = dec.Int()
	(&x.Attack).WeaverUnmarshal(dec)
	(&x.Defense).WeaverUnmarshal(dec)
	x.Multiplier = dec.Float32()
}

var _ codegen.AutoMarshal = &Type{}

func (x *Type) WeaverMarshal(enc *codegen.Encoder) {
	if x == nil {
		panic(fmt.Errorf("Type.WeaverMarshal: nil receiver"))
	}
	enc.Int(x.ID)
	enc.String(x.Name)
}

func (x *Type) WeaverUnmarshal(dec *codegen.Decoder) {
	if x == nil {
		panic(fmt.Errorf("Type.WeaverUnmarshal: nil receiver"))
	}
	x.ID = dec.Int()
	x.Name = dec.String()
}
