name: CI

permissions:
  contents: read

on:
  push:
    branches:
      - main
  pull_request:

env:
  MYSQL_HOST: "127.0.0.1"
  MYSQL_USER: root
  MYSQL_PASS: pass
  MYSQL_DB: pokemon_type

jobs:
  build:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: $MYSQL_PASS
          MYSQL_DATABASE: $MYSQL_DB
          MYSQL_ROOT_HOST: '%'
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin -h127.0.0.1 -uroot -p${MYSQL_ROOT_PASSWORD} ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    strategy:
      matrix:
        go-version:
          - "1.20"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
          cache: true
      - name: Install mysql-client
        run: |
          sudo apt update
          sudo apt install -y mysql-client
      - name: Display Go version
        run: go version
      - name: Prepare mysql seed
        run: make seed
      - name: Build
        run: make
      - name: Test
        run: make test
